### ISSUE TITLE
1.7.0: Library not compiling with AGP8 (Gradle 8)

### ISSUE THREAD

**Issue by marc7garcia** [CanArslanDev/simple_animation_progress_bar#3]
Hi @CanArslanDev !
First of all, thank you so much for your fast response launching the version 1.7.0.
I've tried the current version (1.7.0) and it also fails. This is the compilation error:

Execution failed for task ':simple_animation_progress_bar:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
   > Incorrect package="com.example.simple_aniatiom_progress_bar.simple_animation_progress_bar" found in source AndroidManifest.xml: /Users/marc/.pub-cache/hosted/pub.dev/simple_animation_progress_bar-1.7.0/android/src/main/AndroidManifest.xml.
     Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
     Recommendation: remove package="com.example.simple_aniatiom_progress_bar.simple_animation_progress_bar" from the source AndroidManifest.xml: /Users/marc/.pub-cache/hosted/pub.dev/simple_animation_progress_bar-1.7.0/android/src/main/AndroidManifest.xml.

Please, can you review it?

Thank you so much!

Marc.

**Comment by CanArslanDev** [comment]
Hi @marc7garcia ,
First of all, I'm sorry for the delay, I couldn't get back to you because I had a busy week.
I made a few changes and published the new version (1.8.0) on pub.dev.
You can update this package to version 1.8.0 by typing ```dart pub upgrade simple_animation_progress_bar``` in the terminal.
I would appreciate it if you could give me feedback about the error after trying it with the new version. If the error is not resolved, you can share the newly received error log with me.

Thanks,
Can

**Comment by marc7garcia** [comment]
Hi @CanArslanDev ,
I've tried the new version (1.8.0) and when I do pub get I'm getting the next warning:

The plugin `simple_animation_progress_bar` doesn't have a main class defined in /Users/marc/.pub-cache/hosted/pub.dev/simple_animation_progress_bar-1.8.0/android/src/main/java/com/canarslandev/simple_animation_progress_bar/SimpleAnimationProgressBarPlugin.java or /Users/marc/.pub-cache/hosted/pub.dev/simple_animation_progress_bar-1.8.0/android/src/main/kotlin/com/canarslandev/simple_animation_progress_bar/SimpleAnimationProgressBarPlugin.kt. This is likely to due to an incorrect `androidPackage: com.canarslandev.simple_animation_progress_bar` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.

Please, can you review it?

Thanks,

Marc.

**Comment by CanArslanDev** [comment]
Can you type ```flutter pub cache clean``` and ```flutter pub get``` into the terminal and try again?
or you can also try ``flutter clean`` and ```flutter pub get```

**Comment by marc7garcia** [comment]
I do it.

Same error :(

**Comment by CanArslanDev** [comment]
I have released version 1.8.1, it will probably be downloadable in 10-15 minutes. Can you try that version?

**Comment by marc7garcia** [comment]
Same error in 1.8.1:

The plugin `simple_animation_progress_bar` doesn't have a main class defined in /Users/marc/.pub-cache/hosted/pub.dev/simple_animation_progress_bar-1.8.1/android/src/main/java/com/example/simple_aniatiom_progress_bar/simple_animation_progress_bar/simple_animation_progress_bar/SimpleAnimationProgressBarPlugin.java or /Users/marc/.pub-cache/hosted/pub.dev/simple_animation_progress_bar-1.8.1/android/src/main/kotlin/com/example/simple_aniatiom_progress_bar/simple_animation_progress_bar/simple_animation_progress_bar/SimpleAnimationProgressBarPlugin.kt. This is likely to due to an incorrect `androidPackage: com.example.simple_aniatiom_progress_bar.simple_animation_progress_bar.simple_animation_progress_bar` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile. 

Please, can you paste the pubspec.yaml file? It seems the error is in that file.

Thanks!

**Comment by CanArslanDev** [comment]
Hi @marc7garcia,

Is this an error or does it come as a warning?

Also can you provide the following information?

- Platform you are trying to compile on (mac, win, ios, android)
- Your Flutter version (you can access it by typing ```flutter --version```)

Also, is it possible to open an empty project and send the project if there is the same error there? I think it can be resolved faster if I can test the error myself.

Thanks,
Can

**Comment by marc7garcia** [comment]
Hi @CanArslanDev,

it's an error, because I cannot launch the application.

It doesn't work for both Android and iOS platforms.

I'm using Flutter 3.19.5.

**Comment by CanArslanDev** [comment]
Hi @marc7garcia,

Can you share the pubspec.yaml file?
And when you create a project from scratch, can you check if you still get this error in the ``flutter run`` command?

**Comment by marc7garcia** [comment]
Hi @CanArslanDev,

if I create a new Flutter project and import version 1.8.1, I recieve the same error when I run flutter pub get.

I attach the pubspec.yaml from the new project:

```
name: prueba
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  simple_animation_progress_bar: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
